export const CITY_WEATHER_INFO = "CITY_WEATHER_INFO"
export const UPDATE_CITY_WEATHER = "UPDATE_CITY_WEATHER"
export const LIST_OF_CITIES = "LIST_OF_CITIES"
export const REMOVE_CITY="REMOVE_CITY"
export const ERROR = "ERROR"




